method: grid
metric: 
  goal : maximize 
  name : total_reward
parameters :
  env:
    values : ['ALE/Enduro-v5']
  episodes :
    values : [2000]
  max_steps :
    values : [1200]
  steps :
    values : [6000000]
  epochs :
    values : [1]
  buffer_capacity :
    values : [800000]
  noisyLayer :
    values : [0,1]
  batch_size :
    values : [128]
  random_seed :
    values : [68]
  update_freq :
    values : [4]
  use_checkpoint :
    values : [False]
  dueling:
    values : [False, True]