method: grid
metric: 
  goal : maximize 
  name : total_reward
parameters :
  env:
    values : ['ALE/Pong-v5']
  episodes :
    values : [2000]
  steps :
    values : [2000000]
  epochs :
    values : [1]
  buffer_capacity :
    values : [2000000]
  noisyLayer :
    values : [0,1]
  batch_size :
    values : [32]
  random_seed :
    values : [55, 45, 68]
  update_freq :
    values : [4]